// Copy-pasta from https://github.com/Jonarzz/DotaResponsesRedditBot/blob/master/dota_responses_properties.py
const blacklist = [
  "thank you", "why not?", "glimmer cape", "hood of defiance",
  "mask of madness", "force staff", "armlet of mordiggian",
  "helm of the dominator", "veil of discord", "shadow blade", "blade mail",
  "urn of shadows", "skull basher", "battle fury", "crimson guard",
  "eul's scepter", "eul's scepter of divinity", "scepter of divinity",
  "ethereal blade", "black king bar", "diffusal blade", "lotus orb",
  "silver edge", "solar crest", "medallion of courage", "rod of atos",
  "shiva's guard", "heaven's halberd", "sange and yasha", "monkey king bar",
  "orchid malevolence", "drum of endurance", "aghanim's scepter",
  "manta style", "eye of skadi", "hand of midas", "vladimir's offering",
  "refresher orb", "linken's sphere", "assault cuirass", "divine rapier",
  "scythe of vyse", "sheep stick", "pipe of insight", "boots of travel",
  "blink dagger", "moon shard", "guardian greaves", "octarine core",
  "heart of tarrasque", "abyssal blade", "abyssal underlord",
  "ancient apparition", "anti mage", "bounty hunter", "centaur warrunner",
  "chaos knight", "crystal maiden", "dark seer", "death prophet",
  "dragon knight", "drow ranger", "earth spirit", "earth shaker",
  "elder titan", "ember spirit", "faceless void", "keeper of the light",
  "legion commander", "lone druid", "naga siren", "nature's prophet",
  "natures prophet", "night stalker", "nyx assassin", "ogre magi",
  "outworld destroyer", "phantom assassin", "phantom lancer", "queen of pain",
  "sand king", "shadow demon", "shadow fiend", "skywrath mage",
  "skeleton king", "spirit breaker", "storm spirit", "templar assassin",
  "treant protector", "troll warlord", "vengeful spirit", "winter wyvern",
  "witch doctor", "wraith king", "i agree", "my bad", "ha ha", "why not",
  "fair enough", "no way", "you're welcome", "very nice", "of course",
  "well deserved", "try again", "it worked", "nice try", "seems fair",
  "that's right", "thank god", "thank you so much", "well said", "holy shit",
  "so beautiful", "try harder", "go outside", "arc warden", "he he he",
  "pit lord", "shut up", "how so?", "hey now", "much appreciated",
  "i don't think so", "I know, right?", "it begins", "too soon", "well done",
  "i like it", "are you okay?", "ah, nice", "about time", "very good",
  "are you kidding me?", "at last", "got it", "what happened?", "oh boy",
  "nice one", "i am"
];

module.exports = blacklist;